# Development Environment Configuration
# Deploy with: sam deploy --config-env dev

version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "devops-dashboard-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev LogLevel=debug UpdownWebhookSecret=replace_me UpdownChecksTableNameOverride=alliance-devops-updown-checks-dev UptimeEventsTableNameOverride=alliance-devops-uptime-events-dev DeploymentsTableName=jenkinsexecutions_test DeploymentMetadataTableName=deployment_metadata"
resolve_s3 = true
tags = "Project=\"ALL\" Functionality=\"devops-dashboard\" Environment=\"dev\""

[dev.global.parameters]
stack_name = "devops-dashboard-dev"
